### ISSUE TITLE
Jobs for devs now but can I change to jobs for analysts?

### ISSUE THREAD

**Issue by datatalking** [pogopaule/awesome-sustainability-jobs#23]
I didn’t know this repo existed and it’s such a cool feature to know that I have access to a curated database of sustainably focused companies.

from what I understand this is only for developer jobs is there a way I could monitor or have it search for the same company search but for analyst jobs?

**Comment by pogopaule** [comment]
The entries in the list are handpicked, mostly by me. I searched for companies with at least one open position for a dev. So there is no automation here.

One way that I can imagine to automate your use case is to write some sort of webcrawler that takes the [list of companies](https://github.com/pogopaule/awesome-sustainability-jobs/blob/main/src/data.yaml) as an input and searches the [job sites](https://github.com/pogopaule/awesome-sustainability-jobs/blob/main/src/data.yaml#L23) for keywords (e.g. `analyst`, `data science`).

I remember that there where many companies that also had offerings for data scientists.

You might also want to have a look at the [job portals](https://github.com/pogopaule/awesome-sustainability-jobs#jobportals), especially at [Climatebase](https://climatebase.org/jobs?l=&q=&categories=Data+Analyst&p=0&remote=false)
